select * from cliente;

insert into categoria (nome_categoria,descricao_categoria) values
	('NOME DA CATEGORIA','DESCRIÇÃO DA CATEGORIA'),
	('NOME DA CATEGORIA','DESCRIÇÃO DA CATEGORIA'),
	('NOME DA CATEGORIA','DESCRIÇÃO DA CATEGORIA'),
	('NOME DA CATEGORIA','DESCRIÇÃO DA CATEGORIA'),
	('NOME DA CATEGORIA','DESCRIÇÃO DA CATEGORIA')
;
insert into endereco (pais,uf,cidade,cep,bairro,rua) values
	('NOME DO PAÍS','NOME DA UF','NOME DA CIDADE','NÚMERO DO CEP','NOME DO BAIRRO','NOME DA RUA'),
	('NOME DO PAÍS','NOME DA UF','NOME DA CIDADE','NÚMERO DO CEP','NOME DO BAIRRO','NOME DA RUA'),
	('NOME DO PAÍS','NOME DA UF','NOME DA CIDADE','NÚMERO DO CEP','NOME DO BAIRRO','NOME DA RUA'),
	('NOME DO PAÍS','NOME DA UF','NOME DA CIDADE','NÚMERO DO CEP','NOME DO BAIRRO','NOME DA RUA'),
	('NOME DO PAÍS','NOME DA UF','NOME DA CIDADE','NÚMERO DO CEP','NOME DO BAIRRO','NOME DA RUA')	
;
insert into cliente (nome_completo,nome_de_usuario,email,cpf,data_de_nascimento,cod_endereco) values
	('NOME DO CLIENTE','NOME DO USUÁRIO','EMAIL DO USUÁRIO','CPF DO USUÁRIO','DATA DE NASCIMENTO DO USUÁRIO','CÓDIGO DO ENDEREÇO DO USIÁRIO'),
	('NOME DO CLIENTE','NOME DO USUÁRIO','EMAIL DO USUÁRIO','CPF DO USUÁRIO','DATA DE NASCIMENTO DO USUÁRIO','CÓDIGO DO ENDEREÇO DO USIÁRIO'),
	('NOME DO CLIENTE','NOME DO USUÁRIO','EMAIL DO USUÁRIO','CPF DO USUÁRIO','DATA DE NASCIMENTO DO USUÁRIO','CÓDIGO DO ENDEREÇO DO USIÁRIO'),
	('NOME DO CLIENTE','NOME DO USUÁRIO','EMAIL DO USUÁRIO','CPF DO USUÁRIO','DATA DE NASCIMENTO DO USUÁRIO','CÓDIGO DO ENDEREÇO DO USIÁRIO'),
	('NOME DO CLIENTE','NOME DO USUÁRIO','EMAIL DO USUÁRIO','CPF DO USUÁRIO','DATA DE NASCIMENTO DO USUÁRIO','CÓDIGO DO ENDEREÇO DO USIÁRIO')
;
insert into funcionario (nome_funcionario,cpf_funcionario) values
	('NOME DO FUNCIONÁRIO','CPF DO FUNCIONÁRIO'),
	('NOME DO FUNCIONÁRIO','CPF DO FUNCIONÁRIO'),
	('NOME DO FUNCIONÁRIO','CPF DO FUNCIONÁRIO'),
	('NOME DO FUNCIONÁRIO','CPF DO FUNCIONÁRIO'),
	('NOME DO FUNCIONÁRIO','CPF DO FUNCIONÁRIO')
;